# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b1625128963f5f7321a89c6078a98dd77f787ced984efa9d65f475fa557e8f2e279f3d53c6e8c68a9bb0b07b3230cef4d0d751f093e62688754d5a145a8038f

test:
  secret_key_base: 4d6fff6d9d7cd217d9ab5d4d033eee23eed07e5082eeaadb140af67e15c48d0f9cec3fceec6924a21dbe3b45b44d0009f1184333f4bb3caa873392504aa26c26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
